services:
  database:
    container_name: postgres-db
    image: postgres:17
    env_file:
      - ../.env
    ports:
      - 5432:5432
    volumes:
      - postgres-db_data:/var/lib/postgresql/data
      - ./scripts/create.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ../.env
    ports:
        - 8080:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
  postgres-db_data:
